version: "3"
services:
 
    nginx:
        container_name: nginx-120
        image: unixlinuxgeek/nginx:v1.0
        restart: always
        ports:
            - "80:80"  
        volumes:
            - ./src:/src
            #- ./src/branches/feature/cart/product-isover-notification:/src
            - ./configs/nginx/site_advanced.conf:/etc/nginx/conf.d/default.conf
        networks:
          network_2:
            ipv4_address: 172.120.0.2 
  
    php:
        container_name: php-fpm-120
        image: unixlinuxgeek/php81:v1.0
        working_dir: /src
        restart: always
        volumes:
            - ./src/:/src
            #- ../src/branches/feature/cart/product-isover-notification:/src
            - ./configs/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
          - mysql   
        networks:
          network_2:
            ipv4_address: 172.120.0.3

    mysql:
        container_name: mysql-120
        image: unixlinuxgeek/mysql56alpine
        #command: --default-authentication-plugin=mysql_native_password
        #volumes:
        #    - ./mysql-dumps/megapit_db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: megapit_db
            MYSQL_USER: megapit_db_user
            MYSQL_PASSWORD: 12345678  
        ports:
            - "3306:3306"
        networks:
          network_2:
            ipv4_address: 172.120.0.4

    phpmyadmin:
        image: unixlinuxgeek/phpmyadmin
        container_name: phpmyadmin-120
        environment:
            - UPLOAD_LIMIT=300M
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        ports:
           - 2000:80
        volumes:
           - /sessions
        networks:
          network_2:
            ipv4_address: 172.120.0.5
           
    composer:
        container_name: composer_installation1
        restart: 'no'
        image: unixlinuxgeek/composer
        depends_on:
          - php
        volumes:
           - ./src:/src
        # For Basic App   
        #command: composer create-project --prefer-dist yiisoft/yii2-app-basic project
        
        #command: bash -c "composer create-project --prefer-dist yiisoft/yii2-app-advanced project  && php project/init --env=Development --overwrite=All"
        command: >
           bash -c "composer create-project --prefer-dist yiisoft/yii2-app-advanced /src
           && php /src/init --env=Development --overwrite=All"
        
networks:
  network_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.120.0.0/16
          gateway: 172.120.0.1 
